const S=document.getElementById('screen');
const L={tg:'https://t.me/gonkareski',vk:'https://vk.com/gonkareski',pay:'https://tbank.ru/cf/45FBOgGHgcd'};
const P=[['Футболка Gonkareski','5 000 ₽','👕'],['Худи Gonkareski','7 000 ₽','🧥']];

function home(){S.innerHTML=`<section class="hero"><img src="./car.jpg"><h1>Гонкарески</h1><div class="line"></div><p>Официальное приложение команды. Новости, команда, фан-шоп и поддержка — в одном месте.</p></section><div class="card link" data-p="news"><div class="ico">📰</div><div><b>Новости</b><small>Последние новости команды</small></div></div><div class="card link" data-p="team"><div class="ico">🏎️</div><div><b>О команде</b><small>Пилоты и автомобили</small></div></div><div class="card link" data-p="shop"><div class="ico">🛍️</div><div><b>Фан-шоп</b><small>Одежда команды</small></div></div><div class="card link" data-p="support"><div class="ico">❤️</div><div><b>Поддержать команду</b><small>Поддержка проекта</small></div></div><div class="section-title"><h3>Мы в соцсетях</h3></div><div class="social"><a class="btn blue" href="${L.tg}" target="_blank">Telegram</a><a class="btn light" href="${L.vk}" target="_blank">VK</a></div>`}

function news(){S.innerHTML=`<h2>Новости</h2><div class="card news"><img src="./car.jpg"><div><span class="tag">TELEGRAM</span><h3>Все новости команды</h3><p>Актуальные публикации доступны в официальном Telegram.</p></div></div><a class="btn blue" href="${L.tg}" target="_blank">Открыть Telegram</a>`}

function team(){S.innerHTML=`<h2>О команде</h2><div class="card"><img src="./logo.jpg" style="width:100%;height:110px;object-fit:contain"><p class="muted">Здесь будет история команды, состав, достижения и результаты.</p></div><h3>Пилоты</h3><div class="people"><div class="card person"><img src="./pilot1.jpg"><strong>Максим Доронин</strong><small>Пилот</small></div><div class="card person"><img src="./pilot2.jpg"><strong>Максим Попов</strong><small>Пилот</small></div></div><h3>Автомобиль</h3><div class="card person"><img src="./car.jpg"><strong>Гоночный автомобиль</strong><small>Подробности добавим позже</small></div><h3>Календарь</h3><div class="card empty"><b>🏁</b><strong>Календарь пока пуст</strong><p class="muted">Когда появятся даты соревнований, добавим их сюда.</p></div>`}

function shop(){S.innerHTML='<h2>Фан-шоп</h2><div class="shop">'+P.map((p,i)=>`<div class="card product"><div class="pic">${p[2]}</div><div><b>${p[0]}</b><div class="price">${p[1]}</div><button class="btn" data-order="${i}">Заказать</button></div></div>`).join('')+'</div>'}

function support(){S.innerHTML=`<h2>Поддержать команду</h2><div class="card"><h3>Ваша поддержка помогает нам развиваться!</h3><p class="muted">Выберите сумму и перейдите на страницу поддержки.</p><div class="amounts">${['100 ₽','300 ₽','500 ₽','1 000 ₽','2 000 ₽','Другая'].map((x,i)=>`<button class="amount" ${i==2?'style="background:#0867c8;color:white"':''}>${x}</button>`).join('')}</div><a class="btn" href="${L.pay}" target="_blank">Поддержать команду</a></div>`}

function profile(){S.innerHTML=`<h2>Профиль</h2><div class="card profile"><div class="avatar">🏎️</div><div><b>Гость</b><small class="muted" style="display:block">Профиль команды</small></div></div><div class="social"><a class="btn blue" href="${L.tg}" target="_blank">Telegram</a><a class="btn light" href="${L.vk}" target="_blank">VK</a></div><div class="card" style="margin-top:12px"><b>Гонкарески PWA v1.3</b><p class="muted">Календарь и медиа можно будет пополнять по мере появления материалов.</p></div>`}

function show(p){if(p==='home')home();else if(p==='news')news();else if(p==='team')team();else if(p==='shop')shop();else if(p==='support')support();else profile();document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.p===p));scrollTo(0,0)}

document.addEventListener('click',e=>{let x=e.target.closest('[data-p]');if(x){show(x.dataset.p);return}let o=e.target.closest('[data-order]');if(o){let p=P[o.dataset.order];window.open(L.tg+'?text='+encodeURIComponent('Здравствуйте! Хочу заказать: '+p[0]+' — '+p[1]),'_blank')}});

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error))}
show('home');